config/routes.rb
Rails.application.routes.draw do
  resources :filters
  resources :filter_groups
  resources :select_fields
  resources :odata_requests
  resources :credentials
  resources :collections
  resources :urls
  get 'odata/process_url', to: 'odata#process_url'
  get 'odata/test_url', to: 'odata#test_url'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "collections#index"
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :odata_requests, dependent: :destroy
  has_one :url
  has_one :credential

  broadcasts_refreshes
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :validate_user, only: %i[ show edit update destroy ]
  # GET /collections or /collections.json
  def index

    @collections = Collection.where(user_id: current_user.id)
  end

  # GET /collections/1 or /collections/1.json
  def show
    @odata_request = OdataRequest.new
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections or /collections.json
  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: "Collection was successfully created." }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully updated." }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url, notice: "Collection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

  def validate_user
    if @collection.user_id != current_user.id
      redirect_to root_path
    end
  end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:user_id, :name, :description)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<div  id="<%= dom_id collection %>">
  <div class="min-w-0">
    <div class="flex items-start gap-x-3">
      <p class="text-sm font-semibold leading-6 text-gray-900"><%= collection.name %></p>
    </div>
    <div class="mt-1 flex items-center gap-x-2 text-xs leading-5 text-gray-500">
      <p class="whitespace-nowrap">Updated on <time><%= collection.updated_at.strftime('%m/%d/%y') %></time></p>
      <svg viewBox="0 0 2 2" class="h-0.5 w-0.5 fill-current">
        <circle cx="1" cy="1" r="1" />
      </svg>
      <p class="truncate">Created by <%= collection.user.email %></p>
    </div>
  </div>

</div>

app/views/collections/_form.html.erb
<%= form_with(model: collection, class: "contents") do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md  px-2.5 py-1.5 text-sm text-white font-semibold shadow-sm ring-1 ring-inset bg-blue-600 hover:bg-blue-800", data: {turbo: false} %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing collection</h1>

  <%= render "form", collection: @collection %>

  <%= link_to "Cancel", @collection, class: "rounded-md bg-white px-2.5 py-1.5  font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
</div>

app/views/collections/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Collections" %>

  <%= turbo_frame_tag 'new_collection' do %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Collections</h1>
      <%= link_to "New collection", new_collection_path(collection: @collection), class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
    </div>
  <% end %>
    <div id="collections" class="min-w-full ">
      <div role="list" class="divide-y divide-gray-100">
        <%= turbo_stream_from @collection %>
        <% @collections.each do |collection| %>
          <%= turbo_frame_tag dom_id collection do %>
            <div class="flex my-2 py-2 bg-white rounded-lg items-center justify-between gap-x-6 p-5 ">
              <%= render collection %>
              <div class="flex flex-none items-center gap-x-4">
                <%= link_to 'view collection', collection, class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50", data: {turbo: false} %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

app/views/collections/new.html.erb
<%= turbo_frame_tag 'new_collection' do %>

  <div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New collection</h1>

  <%= render "form", collection: @collection %>

  <%= link_to "Cancel", collections_path, class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
</div>
<% end %>

app/views/collections/show.html.erb
<nav class="flex" aria-label="Breadcrumb">
  <ol role="list" class="flex items-center space-x-4">
    <li>
      <div>
        <%= link_to root_path do %>
        <div class="text-gray-400 hover:text-gray-500">
          <svg class="h-5 w-5 flex-shrink-0" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M9.293 2.293a1 1 0 011.414 0l7 7A1 1 0 0117 11h-1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-3a1 1 0 00-1-1H9a1 1 0 00-1 1v3a1 1 0 01-1 1H5a1 1 0 01-1-1v-6H3a1 1 0 01-.707-1.707l7-7z" clip-rule="evenodd" />
          </svg>
          <span class="sr-only">Home</span>
        </div>
          <% end %>
      </div>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="h-5 w-5 flex-shrink-0 text-gray-300" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
          <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
        </svg>
        <span class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">
<%= @collection.name %>
        </span>
      </div>
    </li>

  </ol>
</nav>
<%= turbo_frame_tag dom_id @collection do %>

  <div class="mx-auto w-full flex my-2 py-2 bg-white rounded-lg p-5 ">

    <div class="">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>
      <div class="flex items-center justify-between gap-x-6 py-5">
        <%= render @collection %>

      </div>
      <%= link_to "Edit this collection", edit_collection_path(@collection), class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50", data: {turbo: false} %>
      <%= link_to "Back to collections", collections_path, class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50", data: {turbo: false} %>
      <div class="inline-block ml-2">
        <%= button_to "Delete this collection", @collection, method: :delete, class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-red-900 shadow-sm ring-1 ring-inset ring-red-300 hover:bg-red-50", data: {turbo: false} %>
      </div>
    </div>


  </div>


  <div class="grid grid-cols-1 items-start gap-4 lg:grid-cols-3 lg:gap-8">
    <div class="grid grid-cols-1 gap-4">
      <section aria-labelledby="section-2-title">
        <h2 class="sr-only" id="section-2-title">Section title</h2>
        <div class="overflow-hidden ">
          <div class="p-6 my-2 rounded-lg bg-white ">
            <%= turbo_frame_tag "url_collection_#{@collection.id}" do %>
              <% if @collection.url.present? %>
                <%= render @collection.url %>
                <%= link_to "edit", edit_url_path(@collection.url), class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>

              <% else %>

                <%= link_to "Add Url", new_url_path(collection: @collection.id), class: " rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
              <% end %>
            <% end %>


          </div>
          <div class="p-6 my-2 rounded-lg bg-white ">
            <%= turbo_frame_tag "credential_collection_#{@collection.id}" do %>
              <% if @collection.credential.present? %>
                <%= render @collection.credential %>
                <div class="grid grid-cols-2 items-start gap-1">
                  <div>
                <%= link_to "edit", edit_credential_path(@collection.credential), class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
                  </div>
                  <div>
                    <%= button_to "delete credentials", @collection.credential, method: :delete, class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-red-900 shadow-sm ring-1 ring-inset ring-red-300 hover:bg-red-50" %>
                  </div>
                </div>
          <% else %>

                <%= link_to "Add Credentials", new_credential_path(collection: @collection.id), class: " rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
              <% end %>
            <% end %>


          </div>
        </div>
      </section>
    </div>
    <div class="grid grid-cols-1 gap-4 lg:col-span-2">
      <section aria-labelledby="section-1-title">
        <h2 class="sr-only" id="section-1-title">Requests</h2>


        <div class="overflow-hidden ">
          <div class="p-6">
            <div data-controller="reveal" data-reveal-hidden-class="hidden">
              <button data-action="click->reveal#toggle"
                      type="button"
                      class="rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">Create New Request</button>

              <div data-reveal-target="item" class="hidden mt-4">
                <%= render 'odata_requests/form', odata_request: @odata_request, collection: @collection.id, url: @collection.url %>
              </div>
            </div>
            <div role="list" class="divide-y divide-gray-100">
              <%= turbo_stream_from @collection %>
              <% @collection.odata_requests.each do |request| %>

                <%= turbo_frame_tag "request_#{request.id}" do %>
                  <%= turbo_stream_from request %>

                  <div class=" my-2 py-2 bg-white rounded-lg items-center gap-x-6 p-5 ">
                    <div class="mt-1">
                      <%= link_to 'view request details', request, class: " rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 " %>
                    </div>
                    <%= render request %>

                  </div>
                <% end %>
              <% end %>
              </div>
          </div>
        </div>
      </section>
    </div>

  </div>
  </div>
<% end %>