config/routes.rb
Rails.application.routes.draw do
  resources :filters
  resources :filter_groups
  resources :select_fields
  resources :odata_requests
  resources :credentials
  resources :collections
  resources :urls
  get 'odata/process_url', to: 'odata#process_url'
  get 'odata/test_url', to: 'odata#test_url'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "collections#index"
end

app/models/filter_group.rb
class FilterGroup < ApplicationRecord
  belongs_to :odata_request, touch: true
  has_many :filters, dependent: :destroy
  broadcasts_refreshes

  after_touch :build_filter_group
  private
  def build_filter_group
    pp filters
    if filters.any?
      self.built_filter_group = ""
      filter_group_array = []
      filters.each do |filter|
        filter_group_array << filter.built_filter
      end
      self.built_filter_group += filter_group_array.join(' and ')
      self.save
    else
      self.built_filter_group = nil
      self.save
    end
    self.odata_request.touch
  end
end

app/controllers/filter_groups_controller.rb
class FilterGroupsController < ApplicationController
  before_action :set_filter_group, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  include ActionView::RecordIdentifier

  # GET /filter_groups or /filter_groups.json

  # GET /filter_groups/1 or /filter_groups/1.json
  def show
  end

  # GET /filter_groups/new
  def new
    @filter_group = FilterGroup.new
  end

  # GET /filter_groups/1/edit
  def edit
  end

  # POST /filter_groups or /filter_groups.json
  def create
    @filter_group = FilterGroup.new(filter_group_params)

    respond_to do |format|
      if @filter_group.save
        format.turbo_stream { render turbo_stream: turbo_stream.append("filter_groups_odata_request_#{@filter_group.odata_request_id}", partial: 'filter_groups/filter_group', locals: { filter_group: @filter_group})}
        format.html { redirect_to @filter_group.odata_request, notice: "Filter group was successfully created." }
        format.json { render :show, status: :created, location: @filter_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @filter_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filter_groups/1 or /filter_groups/1.json
  def update
    respond_to do |format|
      if @filter_group.update(filter_group_params)
        format.html { redirect_to filter_group_url(@filter_group), notice: "Filter group was successfully updated." }
        format.json { render :show, status: :ok, location: @filter_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @filter_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filter_groups/1 or /filter_groups/1.json
  def destroy
    odata_request = @filter_group.odata_request

    @filter_group.destroy
    respond_to do |format|
      format.turbo_stream { render(turbo_stream: turbo_stream.remove(dom_id(@filter_group))) }
      format.html { redirect_to odata_request, notice: "Filter group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filter_group
      @filter_group = FilterGroup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def filter_group_params
      params.require(:filter_group).permit(:odata_request_id, :built_filter_group)
    end
end

app/helpers/filter_groups_helper.rb
module FilterGroupsHelper
end

app/views/filter_groups/_filter_group.html.erb
<%= turbo_frame_tag dom_id(filter_group)  do %>
  <div class="p-4 mt-2 rounded-md bg-white">
    <dl class="divide-y divide-gray-100">
      <div class="px-4 py-2">
        <dt class="text-sm font-medium leading-6 text-gray-900">
          <div class="my-5">
            <div data-controller="reveal" data-reveal-hidden-class="hidden" class="my-4">
              <button data-action="click->reveal#toggle" type="button" class="rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">add filter +</button>

              <div data-reveal-target="item" class="hidden mt-4">
                <%= render partial: 'filters/form', locals: { filter: Filter.new(filter_group_id: filter_group.id) } %>
              </div>
            </div>

            <% if filter_group.filters.present? %>
              <%= turbo_frame_tag "filters_filter_group_#{filter_group.id}" do %>
              <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                  <table class="min-w-full divide-y divide-gray-100 bg-white">
                    <thead>
                    <tr class="bg-stone-50">
                      <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-3">field</th>
                      <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">operator</th>
                      <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">value</th>
                      <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-3">
                        <span class="sr-only"></span>
                      </th>
                    </tr>
                    </thead>
                    <tbody class="bg-white">
                    <%= render filter_group.filters %>
                    </tbody>
                  </table>
                </div>
              </div>
            <% end %>
            <% end %>

          </div>
        </dt>

      </div>
      <dd class="mt-1 pt-2 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
        <%= button_to "remove filter group", filter_group, method: :delete, class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-red-900 shadow-sm ring-1 ring-inset ring-red-300 hover:bg-red-50" %>
      </dd>
    </dl>
  </div>
<% end %>

app/views/filter_groups/_form.html.erb
<%= form_with(model: filter_group, class: "contents") do |form| %>
  <% if filter_group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(filter_group.errors.count, "error") %> prohibited this filter_group from being saved:</h2>

      <ul>
        <% filter_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :odata_request_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>


  <div class="inline">
    <%= form.submit class: "rounded-md  px-2.5 py-1.5 text-sm text-white font-semibold shadow-sm ring-1 ring-inset bg-blue-600 hover:bg-blue-800" %>
  </div>
<% end %>

app/views/filter_groups/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing filter group</h1>

  <%= render "form", filter_group: @filter_group %>

  <%= link_to "Show this filter group", @filter_group, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to filter groups", filter_groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/filter_groups/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Filter groups" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Filter groups</h1>
    <%= link_to "New filter group", new_filter_group_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="filter_groups" class="min-w-full">
    <% @filter_groups.each do |filter_group| %>
      <%= render filter_group %>
      <p>
        <%= link_to "Show this filter group", filter_group, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/filter_groups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New filter group</h1>

  <%= render "form", filter_group: @filter_group %>

  <%= link_to "Back to filter groups", filter_groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/filter_groups/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @filter_group %>

    <%= link_to "Edit this filter group", edit_filter_group_path(@filter_group), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to filter groups", filter_groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this filter group", @filter_group, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>