config/routes.rb
Rails.application.routes.draw do
  resources :filters
  resources :filter_groups
  resources :select_fields
  resources :odata_requests
  resources :credentials
  resources :collections
  resources :urls
  get 'odata/process_url', to: 'odata#process_url'
  get 'odata/test_url', to: 'odata#test_url'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "collections#index"
end

app/models/filter.rb
class Filter < ApplicationRecord
  belongs_to :filter_group, touch: true
  before_save :build_filter

  def build_filter
    self.built_filter = "#{self.filter_field} #{self.operator} #{self.filter_value}"
  end

end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :set_filter, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /filters or /filters.json

  # GET /filters/1 or /filters/1.json
  def show
  end

  # GET /filters/new
  def new
    @filter = Filter.new
  end

  # GET /filters/1/edit
  def edit
  end

  # POST /filters or /filters.json
  def create
    @filter = Filter.new(filter_params)
    puts "It didn't hit the save state"

    respond_to do |format|
      if @filter.save
        puts "It hit the save state"
        format.turbo_stream { render turbo_stream: turbo_stream.replace(dom_id(@filter.filter_group), partial: 'filter_groups/filter_group', locals: { filter_group: @filter.filter_group})}
        format.html { redirect_to @filter.filter_group.odata_request, notice: "Filter was successfully created." }
        format.json { render :show, status: :created, location: @filter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
        pp @filter.errors
      end
    end
  end

  # PATCH/PUT /filters/1 or /filters/1.json
  def update
    respond_to do |format|
      if @filter.update(filter_params)
        format.html { redirect_to filter_url(@filter), notice: "Filter was successfully updated." }
        format.json { render :show, status: :ok, location: @filter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filters/1 or /filters/1.json
  def destroy
    @filter.destroy!

    respond_to do |format|
      format.turbo_stream { render(turbo_stream: turbo_stream.remove(dom_id(@filter))) }
      format.html { redirect_to odata_request, notice: "Filter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filter
      @filter = Filter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def filter_params
      params.require(:filter).permit(:filter_group_id, :filter_field, :operator, :filter_value, :built_filter)
    end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/filters/_filter.html.erb
<tr class="even:bg-stone-50" id="<%= dom_id filter %>">
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-xs font-medium text-gray-900 sm:pl-3"><%= filter.filter_field %></td>
  <td class="whitespace-nowrap px-3 py-4 text-xs text-gray-500"><%= filter.operator %></td>
  <td class="whitespace-nowrap px-3 py-4 text-xs text-gray-500"><%= filter.filter_value %></td>
  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-3">
    <%= button_to "remove filter", filter, method: :delete, class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  </td>
</tr>

app/views/filters/_form.html.erb
<%= form_with(model: filter, class: "contents") do |form| %>
  <% if filter.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(filter.errors.count, "error") %> prohibited this filter from being saved:</h2>

      <ul>
        <% filter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <%= form.hidden_field :filter_group_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>

  <div class="my-5">
    <%= form.label :filter_field %>
    <%= form.text_field :filter_field, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :operator %>
    <%= form.select :operator,[['eq (=)','eq'],['gt (>)','gt'],['lt (<)','lt'],['ge (>=)','ge'],['le (<=)','le'],['ne (<>)','ge']],{ prompt: 'select one'}, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :filter_value %>
    <%= form.text_field :filter_value, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md  px-2.5 py-1.5 text-sm text-white font-semibold shadow-sm ring-1 ring-inset bg-blue-600 hover:bg-blue-800" %>
  </div>
<% end %>

<div data-controller="modal datetime" class="my-4">
  <dialog data-modal-target="dialog" class="p-8 rounded-lg backdrop:bg-black/80 min-w-56">
    <p class=" font-semibold leading-6 text-gray-900">DateTime Helper</p>
    <p class="text-xs leading-6 text-gray-600">Input a Date & Time value to get the Pelican accepted format</p>

    <div data-controller="clipboard" data-clipboard-success-content-value="Copied!" class="mt-1 text-xs leading-5 text-gray-500 w-full block">
      <p class="text-sm mt-2 leading-6 text-gray-900">Input:</p>

      <input data-datetime-target="input" data-action="input->datetime#updateFormattedInput" type="datetime-local" class="font-mono min-h-12 text-xs w-full text-gray-200 bg-slate-800 shadow rounded-md outline-none" />

      <p class="mt-2 text-sm leading-6 text-gray-900">Formatted date:</p>

      <input data-datetime-target="formattedInput" data-clipboard-target="source" type="text" readonly class="font-mono min-h-12 text-xs w-full text-gray-200 bg-slate-800 shadow rounded-md outline-none mb-2" />
      <button type="button" data-action="clipboard#copy" data-clipboard-target="button">Copy to clipboard</button>
    </div>
    <button autofocus data-action="modal#close" class="mt-4 rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">Close</button>
  </dialog>

  <button data-action="modal#open" class="rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">date/time helper</button>
</div>

app/views/filters/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing filter</h1>

  <%= render "form", filter: @filter %>

  <%= link_to "Show this filter", @filter, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to filters", filters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/filters/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Filters" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Filters</h1>
    <%= link_to "New filter", new_filter_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="filters" class="min-w-full">
    <% @filters.each do |filter| %>
      <%= render filter %>
      <p>
        <%= link_to "Show this filter", filter, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/filters/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New filter</h1>

  <%= render "form", filter: @filter %>

  <%= link_to "Back to filters", filters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/filters/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @filter %>

    <%= link_to "Edit this filter", edit_filter_path(@filter), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to filters", filters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this filter", @filter, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>