config/routes.rb
Rails.application.routes.draw do
  resources :filters
  resources :filter_groups
  resources :select_fields
  resources :odata_requests
  resources :credentials
  resources :collections
  resources :urls
  get 'odata/process_url', to: 'odata#process_url'
  get 'odata/test_url', to: 'odata#test_url'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "collections#index"
end

app/models/select_field.rb
class SelectField < ApplicationRecord
  belongs_to :odata_request, touch: true
  broadcasts_refreshes

end

app/controllers/select_fields_controller.rb
class SelectFieldsController < ApplicationController
  before_action :set_select_field, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /select_fields or /select_fields.json


  # GET /select_fields/1 or /select_fields/1.json
  def show
  end

  # GET /select_fields/new
  def new
    @odata_request = params[:odata_request]
    @select_field = SelectField.new
  end

  # GET /select_fields/1/edit
  def edit
  end

  # POST /select_fields or /select_fields.json
  def create
    @select_field = SelectField.new(select_field_params)

    respond_to do |format|
      if @select_field.save
        format.html { redirect_to @select_field.odata_request, notice: "Select field was successfully created." }
        format.json { render :show, status: :created, location: @select_field }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @select_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /select_fields/1 or /select_fields/1.json
  def update
    respond_to do |format|
      if @select_field.update(select_field_params)
        format.html { redirect_to @select_field.odata_request, notice: "Select field was successfully updated." }
        format.json { render :show, status: :ok, location: @select_field }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @select_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /select_fields/1 or /select_fields/1.json
  def destroy
    odata_request = @select_field.odata_request
    @select_field.destroy

    respond_to do |format|
      format.html { redirect_to odata_request, notice: "Select field was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_select_field
      @select_field = SelectField.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def select_field_params
      params.require(:select_field).permit(:field_name, :odata_request_id)
    end
end

app/helpers/select_fields_helper.rb
module SelectFieldsHelper
end

app/views/select_fields/_form.html.erb
<%= form_with(model: select_field, class: "contents") do |form| %>
  <% if select_field.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(select_field.errors.count, "error") %> prohibited this select_field from being saved:</h2>

      <ul>
        <% select_field.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :field_name %>
    <%= form.text_field :field_name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

    <%= form.hidden_field :odata_request_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>


  <div class="inline">
    <%= form.submit class: "rounded-md  px-2.5 py-1.5 text-sm text-white font-semibold shadow-sm ring-1 ring-inset bg-blue-600 hover:bg-blue-800" %>
  </div>
<% end %>

app/views/select_fields/_select_field.html.erb
<div id="<%= dom_id select_field %>">
  <div class="mt-2 border-t border-gray-100">
    <dl class="divide-y divide-gray-100">
      <div class="px-4 py-2 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-sm font-medium leading-6 text-gray-900"><%= select_field.field_name %></dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">      <%= button_to "remove field", select_field, method: :delete, class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
        </dd>
      </div>
    </dl>
  </div>

</div>

app/views/select_fields/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing select field</h1>

  <%= render "form", select_field: @select_field %>

  <%= link_to "Show this select field", @select_field, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to select fields", select_fields_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/select_fields/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Select fields" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Select fields</h1>
    <%= link_to "New select field", new_select_field_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="select_fields" class="min-w-full">
    <% @select_fields.each do |select_field| %>
      <%= render select_field %>
      <p>
        <%= link_to "Show this select field", select_field, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/select_fields/new.html.erb
<%= turbo_frame_tag "new_select_field" do %>

  <div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New select field</h1>

  <%= render "form", select_field: @select_field, odata_request: @odata_request %>

  <%= link_to "Back to select fields", select_fields_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
<% end %>

app/views/select_fields/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @select_field %>

    <%= link_to "Edit this select field", edit_select_field_path(@select_field), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to select fields", select_fields_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this select field", @select_field, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>